title: Excelente Web Developer
author: Luis Davila
email: your-email@domain.com
description: #closes 2

# social links
twitter_username: lufdate
github_username:  DavilaLuis

show_excerpts: false # set to false to remove excerpts on the homepage
theme : minima
