title: El mejor Programador Web
author: Luis Davila
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Closes #2.

# social links
twitter_username: lufdate
github_username:  DavilaLuis

show_excerpts: true # set to false to remove excerpts on the homepage
theme : minima
