title: El Mejor Web Developer
author: DavilaLuis
email: your-email@domain.com
description: > #closes 2

# social links
twitter_username: lufdate
github_username:  DavilaLuis

show_excerpts: true # set to false to remove excerpts on the homepage
theme : minima
